require('dotenv').config();

module.exports = {
  BaseUrl: process.env.BaseUrl,
  BotToken:process.env.BotToken,
  SecretToken:process.env.SecretToken,
  ServerId:process.env.ServerId,
  avatar :process.env.avatar,
  avatarNoImage: process.env.avatarNoImage,
  MyId:process.env.MyId,
  IdMessagePolicy:process.env.IdMessagePolicy,
  IdAnnouncement30Days:process.env.IdAnnouncement30Days,
  BotId :process.env.BotId,
  IdRoleMember:process.env.IdRoleMember,
  IdRoleNewMember:process.env.IdRoleNewMember,
  IdRoleBookClub:process.env.IdRoleBookClub,
  IdRole7Streak:process.env.IdRole7Streak,
  IdRole30Streak:process.env.IdRole30Streak,
  IdRole100Streak:process.env.IdRole100Streak,
  IdRole365Streak:process.env.IdRole365Streak,
  IdRole30DaysChallenge: process.env.IdRole30DaysChallenge,
  IdRoleChallenger: process.env.IdRoleChallenger,
  IdChannelWelcome:process.env.IdChannelWelcome,
  IdChannelSchedule:process.env.IdChannelSchedule,
  IdChannelWeeklyGoals:process.env.IdChannelWeeklyGoals,
  IdChannelPolicy:process.env.IdChannelPolicy,
  IdChannelGuidelines:process.env.IdChannelGuidelines,
  IdChannelDone:process.env.IdChannelDone,
  IdChannelWaitlist:process.env.IdChannelWaitlist,
  IdChannelHighlight :process.env.IdChannelHighlight ,
  IdChannelBookClub:process.env.IdChannelBookClub,
  IdChannelActivity : process.env.IdChannelActivity,
  IdFocusGroup:process.env.IdFocusGroup,
  TimeBookClupOpened:process.env.TimeBookClupOpened,
  TimeBookClubEnded:process.env.TimeBookClubEnded
};
